apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: ordersystem-ms-payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersystem-ms-payments-deployment
  template:
    metadata:
      labels:
        app: ordersystem-ms-payments-deployment
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: order-system-ms-payments-api-container
          command: ["/bin/sh", "-c", "env"]
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-configmap
