version: '4.34.3'

services:
  mysqldbPayments:
    image: mysql:latest
    container_name: dbMySql-payments
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_LOCAL_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - orderSystem

  api:
    depends_on:
      - mysqldbPayments
    container_name: nestjs
    image: nestjs-payments
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - TOKEN_MERCADO_PAGO=$TOKEN_MERCADO_PAGO
      - USERID=$USERID
      - POSID=$POSID
      - ENDPOINT=$ENDPOINT
      - QUEUE_RECEIVE_ORDER=$QUEUE_RECEIVE_ORDER
      - QUEUE_SEND_ORDER=$QUEUE_SEND_ORDER
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN

    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - orderSystem

volumes:
  db:
networks:
  orderSystem:
    driver: bridge
