name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run tests e2e
        run: |
          yarn test:e2e

      - name: Run tests unit
        run: |
          yarn test:unit

      - name: Run tests integration
        run: |
          yarn test:integration

  # sonar:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Run SonarQube Scan
  #       uses: sonarsource/sonar-scanner-action@v2.0.0
  #       with:
  #         sonar-project-key: seu_projeto
  #         sonar-host-url: http://seu-sonarqube:9000
  #         sonar-login: ${{ secrets.SONAR_TOKEN }} # Adicione o token nas secrets do seu repositório
  #         sonar-scanner-options: |
  #           -Dsonar.sources=.
  #           -Dsonar.language=js
  #           -Dsonar.tests=.
  #           -Dsonar.test.inclusions=**/*.spec.ts  # Altere conforme sua estrutura de testes
